import AlternatingAnalytic.Algebra.DeterminantQuadraticGrading

noncomputable section
open scoped BigOperators

namespace AlternatingAnalytic.DeterminantQuadratic
variable (K : Type*) [Field K] (p : ℕ)

@[simp] theorem genPoly_linear (i r : Fin p) :
    genPoly K p (Sum.inr (Sum.inl i)) r = toeplitz K p r i := by
  classical
  simp only [genPoly]
  unfold toeplitz
  split_ifs with h
  · rw [Finset.sum_eq_single (⟨r.val - i.val, by omega⟩ : Fin p)]
    · simp [Nat.add_sub_of_le h]
    · intro b _ hb
      have hn : i.val + b.val ≠ r.val := by
        intro he
        apply hb
        apply Fin.ext
        dsimp
        omega
      simp [hn]
    · simp
  · apply Finset.sum_eq_zero
    intro b _
    have hn : i.val + b.val ≠ r.val := by omega
    simp [hn]

theorem minor_mem_quadraticSpan (r s i j : Fin p) :
    minor K p r s i j ∈ quadraticSpan K p :=
  Submodule.subset_span (Or.inl ⟨r, s, i, j, rfl⟩)

theorem squareCoordinate_mem_quadraticSpan (r : Fin p) :
    squareCoordinate K p r ∈ quadraticSpan K p :=
  Submodule.subset_span (Or.inr ⟨r, rfl⟩)

/-- Degree counting and Laplace expansion reduce every quadratic generator determinant
    to the span of the Toeplitz minors and square coordinates. The row selector is
    arbitrary so this induction also covers all repeated-standard-column zero cases. -/
theorem det_genPoly_degree_two_mem (n : ℕ) (rows : Fin n → Fin p)
    (s : Fin n → GeneratorIndex p)
    (hdeg : ∑ j, generatorDegree p (s j) = 2) :
    Matrix.det (Matrix.of (fun i j => genPoly K p (s j) (rows i))) ∈ quadraticSpan K p := by
  classical
  induction n with
  | zero => simp at hdeg
  | succ n ih =>
    by_cases hz : ∃ j i, s j = Sum.inl i
    · obtain ⟨j, k, hj⟩ := hz
      rw [Matrix.det_succ_column _ j]
      apply Submodule.sum_mem
      intro i _
      have hd : ∑ a : Fin n, generatorDegree p (s (j.succAbove a)) = 2 := by
        rw [Fin.sum_univ_succAbove _ j, hj] at hdeg
        simpa [generatorDegree] using hdeg
      have hm := ih (fun a => rows (i.succAbove a)) (fun a => s (j.succAbove a)) hd
      by_cases hk : k = rows i
      · simp only [Matrix.of_apply, hj, genPoly, hk, ite_true, mul_one]
        convert (quadraticSpan K p).smul_mem ((-1 : K) ^ ((i : ℕ) + (j : ℕ))) hm using 1
        simp [Matrix.submatrix, MvPolynomial.smul_eq_C_mul]
        rfl
      · simp [hj, genPoly, hk]
    · have hpos : ∀ j, 1 ≤ generatorDegree p (s j) := by
        intro j
        cases hs : s j with
        | inl i => exact False.elim (hz ⟨j, i, hs⟩)
        | inr t => cases t <;> simp [generatorDegree]
      have hn : n + 1 ≤ 2 := by
        have hh := Finset.sum_le_sum (s := Finset.univ) (fun j _ => hpos j)
        simpa [hdeg] using hh
      match n with
      | 0 =>
        have hd : generatorDegree p (s 0) = 2 := by simpa using hdeg
        cases hs : s 0 with
        | inl i => simp [hs, generatorDegree] at hd
        | inr t =>
          cases t with
          | inl i => simp [hs, generatorDegree] at hd
          | inr u =>
            simpa [Matrix.det_unique, hs, genPoly, squareCoordinate] using
              squareCoordinate_mem_quadraticSpan K p (rows 0)
      | 1 =>
        have hd : generatorDegree p (s 0) + generatorDegree p (s 1) = 2 := by
          simpa [Fin.sum_univ_two] using hdeg
        have hd0 : generatorDegree p (s 0) = 1 := by
          have hp1 := hpos (1 : Fin 2)
          have hp0 := hpos (0 : Fin 2)
          omega
        have hd1 : generatorDegree p (s 1) = 1 := by
          have hp0 := hpos (0 : Fin 2)
          omega
        have hlin (a : Fin 2) (ha : generatorDegree p (s a) = 1) :
            ∃ i, s a = Sum.inr (Sum.inl i) := by
          cases hs : s a with
          | inl i => simp [hs, generatorDegree] at ha
          | inr t =>
            cases t with
            | inl i => exact ⟨i, rfl⟩
            | inr u => simp [hs, generatorDegree] at ha
        obtain ⟨i, hi⟩ := hlin 0 hd0
        obtain ⟨j, hj⟩ := hlin 1 hd1
        simpa [Matrix.det_fin_two, hi, hj, minor] using
          minor_mem_quadraticSpan K p (rows 0) (rows 1) i j
      | n + 2 => omega

theorem detPoly_degree_two_mem_quadraticSpan (s : Fin p → GeneratorIndex p)
    (hdeg : ∑ j, generatorDegree p (s j) = 2) :
    detPoly K p s ∈ quadraticSpan K p :=
  det_genPoly_degree_two_mem K p p id s hdeg

/-- Repeated standard columns give zero, without any assumption on characteristic. -/
theorem detPoly_eq_zero_of_repeated_standard (s : Fin p → GeneratorIndex p)
    (j k i : Fin p) (hjk : j ≠ k) (hj : s j = Sum.inl i) (hk : s k = Sum.inl i) :
    detPoly K p s = 0 := by
  apply Matrix.det_zero_of_column_eq hjk
  intro r
  simp [Matrix.of_apply, hj, hk]

/-- The degree-two component of the actual determinant span is generated by the
    concrete Toeplitz minors and the actual ordered convolution coordinates. -/
theorem homogeneousComponent_two_mem_quadraticSpan {P : Poly K p}
    (hP : P ∈ G0poly K p) :
    MvPolynomial.homogeneousComponent 2 P ∈ quadraticSpan K p := by
  classical
  induction hP using Submodule.span_induction with
  | mem Q hQ =>
    obtain ⟨s, rfl⟩ := hQ
    rw [MvPolynomial.homogeneousComponent_of_mem (detPoly_isHomogeneous K p s)]
    split_ifs with h
    · exact detPoly_degree_two_mem_quadraticSpan K p s h.symm
    · exact Submodule.zero_mem _
  | zero => simp
  | add Q R hQ hR ihQ ihR => simpa using (quadraticSpan K p).add_mem ihQ ihR
  | smul c Q hQ ihQ => simpa using (quadraticSpan K p).smul_mem c ihQ

end AlternatingAnalytic.DeterminantQuadratic
