import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.LinearAlgebra.Finsupp.LinearCombination
import Mathlib.LinearAlgebra.FiniteDimensional.Defs

/-!
# Finite generators for determinant spaces

Multilinearity expands determinants of vectors in a finite span into determinants
of tuples of the displayed generators. All spans below are over the smaller field.
-/

namespace AlternatingAnalytic

open scoped BigOperators

section Multilinear

variable {K A B J ι : Type*} [Field K] [AddCommGroup A] [Module K A]
  [AddCommGroup B] [Module K B] [Fintype J] [Fintype ι] [DecidableEq ι]

/-- Expanding every input in a finite generating family expands the output into
the span of the generator tuples. -/
theorem multilinear_mem_span_generator_tuples
    (f : MultilinearMap K (fun _ : ι => A) B) (gen : J → A) (v : ι → A)
    (hv : ∀ i, v i ∈ Submodule.span K (Set.range gen)) :
    f v ∈ Submodule.span K (Set.range (fun s : ι → J => f (fun i => gen (s i)))) := by
  classical
  choose c hc using fun i => (Submodule.mem_span_range_iff_exists_fun K).mp (hv i)
  have heq : v = fun i => ∑ j, c i j • gen j := funext fun i => (hc i).symm
  rw [heq, f.map_sum]
  apply Submodule.sum_mem
  intro s _
  rw [f.map_smul_univ]
  exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_range_self s))

/-- The output span of a multilinear map on a finitely generated submodule is
generated by the tuples of its given generators. -/
theorem multilinear_span_generator_tuples
    (f : MultilinearMap K (fun _ : ι => A) B) (gen : J → A) :
    Submodule.span K (Set.range (fun v : ι → Submodule.span K (Set.range gen) =>
      f (fun i => (v i : A)))) =
    Submodule.span K (Set.range (fun s : ι → J => f (fun i => gen (s i)))) := by
  apply le_antisymm
  · apply Submodule.span_le.mpr
    rintro _ ⟨v, rfl⟩
    exact multilinear_mem_span_generator_tuples f gen _ (fun i => (v i).property)
  · apply Submodule.span_le.mpr
    rintro _ ⟨s, rfl⟩
    apply Submodule.subset_span
    exact ⟨fun i => ⟨gen (s i), Submodule.subset_span (Set.mem_range_self (s i))⟩, rfl⟩

end Multilinear

section Determinant

variable {K L A J : Type*} [Field K] [Field L] [Algebra K L]
  [AddCommGroup A] [Module K A] [Module L A] [IsScalarTower K L A]
  {p : ℕ} [Fintype J]

/-- The column determinant of the coordinate vectors, as a multilinear map over K. -/
noncomputable def coordinateColumnDeterminant (coord : A →ₗ[L] (Fin p → L)) :
    MultilinearMap K (fun _ : Fin p => A) L :=
  ((Matrix.detRowAlternating.compLinearMap coord).toMultilinearMap).restrictScalars K

theorem coordinateColumnDeterminant_apply (coord : A →ₗ[L] (Fin p → L))
    (v : Fin p → A) :
    coordinateColumnDeterminant (K := K) coord v = Matrix.det (fun i j => coord (v j) i) := by
  change Matrix.det (fun i j => coord (v i) j) = _
  exact Matrix.det_transpose _ |>.symm

/-- Determinants of tuples from the span of a finite family are spanned by the
determinants of tuples of that same family, with columns in the source convention. -/
theorem determinant_span_generator_tuples (coord : A →ₗ[L] (Fin p → L)) (gen : J → A) :
    Submodule.span K (Set.range (fun v : Fin p → Submodule.span K (Set.range gen) =>
      Matrix.det (fun i j => coord (v j : A) i))) =
    Submodule.span K (Set.range (fun s : Fin p → J =>
      Matrix.det (fun i j => coord (gen (s j)) i))) := by
  simpa only [coordinateColumnDeterminant_apply] using
    multilinear_span_generator_tuples (coordinateColumnDeterminant (K := K) coord) gen

/-- The determinant space of a finitely generated input space is finite dimensional
over K; neither field nor the input space is required to be complete. -/
theorem finiteDimensional_determinant_span (coord : A →ₗ[L] (Fin p → L)) (gen : J → A) :
    FiniteDimensional K (Submodule.span K (Set.range
      (fun v : Fin p → Submodule.span K (Set.range gen) =>
        Matrix.det (fun i j => coord (v j : A) i)))) := by
  rw [determinant_span_generator_tuples coord gen]
  exact FiniteDimensional.span_of_finite K (Set.finite_range _)

end Determinant

end AlternatingAnalytic
