import AlternatingAnalytic.Analysis.LaurentSubfieldExtra.LaurentExpansion
import AlternatingAnalytic.Analysis.LaurentSubfieldExtra.LaurentPolynomialNorm
import AlternatingAnalytic.Analysis.LaurentSubfieldProperties

/-!
# The Laurent subfield is the closure of `𝔽_p(t)`

Lemma D.2(3) and (4). In a complete normed field `K` of characteristic `p`, an element `t` with
`‖t‖ = r ∈ (0, 1)` gives an isometric ring homomorphism `ev_t : 𝔽_p((X)) → K` with `‖X‖ = r`,
evaluating each series termwise at `t`. Its image is the closure of `𝔽_p(t)`, and this closure
is spherically complete.
-/

noncomputable section

set_option backward.isDefEq.respectTransparency false

open scoped NNReal

namespace AlternatingAnalytic

variable {K : Type*} [NormedField K] (p : ℕ) [Fact p.Prime] [CharP K p]

/-- The image of `𝔽_p` lies in every subfield of a field of characteristic `p`. -/
theorem zmod_castHom_mem_subfield (S : Subfield K) (c : ZMod p) :
    ZMod.castHom (dvd_refl p) K c ∈ S := by
  rw [← ZMod.natCast_zmod_val c, map_natCast]
  exact natCast_mem S c.val

/-- Polynomials over `𝔽_p` evaluated at `t` lie in the subfield generated by `t`. -/
theorem eval₂_zmod_mem_subfieldClosure (t : K) (P : Polynomial (ZMod p)) :
    P.eval₂ (ZMod.castHom (dvd_refl p) K) t ∈ Subfield.closure {t} := by
  induction P using Polynomial.induction_on' with
  | add P Q hP hQ => rw [Polynomial.eval₂_add]; exact add_mem hP hQ
  | monomial n c =>
    rw [Polynomial.eval₂_monomial]
    exact mul_mem (zmod_castHom_mem_subfield p _ c)
      (pow_mem (Subfield.subset_closure (Set.mem_singleton t)) n)

variable (r : ℝ≥0)

/-- An evaluation of rational functions sending `X` to `t` has image `Subfield.closure {t}`. -/
theorem fieldRange_ratFunc_eq_subfieldClosure (t : K) (g : LaurentField (ZMod p) r →+* K)
    (hc : ∀ c, g (algebraMap (ZMod p) (LaurentField (ZMod p) r) c) =
      ZMod.castHom (dvd_refl p) K c)
    (hX : g (polynomialToLaurentField (ZMod p) r Polynomial.X) = t) :
    (g.comp (ratFuncToLaurentField (ZMod p) r)).fieldRange = Subfield.closure {t} := by
  have hpoly (P : Polynomial (ZMod p)) :
      g.comp (ratFuncToLaurentField (ZMod p) r)
          (algebraMap (Polynomial (ZMod p)) (RatFunc (ZMod p)) P) =
        P.eval₂ (ZMod.castHom (dvd_refl p) K) t := by
    rw [RingHom.comp_apply, ratFuncToLaurentField_polynomial,
      polynomialToLaurentField_eq_eval₂]
    change g (Polynomial.eval₂ _ _ P) = _
    rw [Polynomial.hom_eval₂, hX]
    congr 1
    ext c
    exact hc c
  apply le_antisymm
  · rintro _ ⟨q, rfl⟩
    induction q using RatFunc.induction_on with
    | f P Q hQ =>
      rw [map_div₀, hpoly, hpoly]
      exact div_mem (eval₂_zmod_mem_subfieldClosure p t P)
        (eval₂_zmod_mem_subfieldClosure p t Q)
  · refine Subfield.closure_le.mpr (Set.singleton_subset_iff.mpr
      ⟨algebraMap (Polynomial (ZMod p)) (RatFunc (ZMod p)) Polynomial.X, ?_⟩)
    rw [hpoly, Polynomial.eval₂_X]

variable [Fact (0 < r)] [Fact (r < 1)] [CompleteSpace K]

/-- Lemma D.2(3): the isometric evaluation `ev_t : 𝔽_p((X)) → K` is termwise evaluation at
`t`, and its image is the closed subfield `closure 𝔽_p(t)`. -/
theorem exists_laurentField_evaluation (t : K) (ht : ‖t‖ = r) :
    ∃ ev : LaurentField (ZMod p) r →+* K,
      Continuous ev ∧ Isometry ev ∧
      (∀ x : LaurentField (ZMod p) r,
        HasSum (fun i : ℤ => ZMod.castHom (dvd_refl p) K (LaurentField.coeff (ZMod p) r i x) *
          t ^ i) (ev x)) ∧
      IsClosed (ev.fieldRange : Set K) ∧
      (ev.fieldRange : Set K) = closure (Subfield.closure {t} : Set K) := by
  let : IsUltrametricDist K := charP_isUltrametricDist p
  obtain ⟨g, hg, hclosed, hdense, hc, hX⟩ := exists_isometric_laurentField_embedding (ZMod p) r
    (ZMod.castHom (dvd_refl p) K) t ht
  refine ⟨g, hg.continuous, hg,
    hasSum_eval_of_continuous (ZMod p) r g hg.continuous _ t hc hX, ?_, ?_⟩
  · rwa [RingHom.coe_fieldRange]
  · rw [RingHom.coe_fieldRange, ← hdense, ← fieldRange_ratFunc_eq_subfieldClosure p r t g hc hX,
      RingHom.coe_fieldRange]

include p in
/-- Lemma D.2(4): the closure of `𝔽_p(t)` is spherically complete when `0 < ‖t‖ < 1`. -/
theorem sphericallyCompleteSpace_closure_subfieldClosure (t : K) (ht0 : 0 < ‖t‖)
    (ht1 : ‖t‖ < 1) :
    SphericallyCompleteSpace (closure (Subfield.closure {t} : Set K)) := by
  let : IsUltrametricDist K := charP_isUltrametricDist p
  let : Fact (0 < ‖t‖₊) := ⟨ht0⟩
  let : Fact (‖t‖₊ < 1) := ⟨ht1⟩
  obtain ⟨g, -, hg, -, -, hrange⟩ := exists_laurentField_evaluation p ‖t‖₊ t rfl
  rw [← hrange]
  exact (laurentField_range_properties (ZMod p) ‖t‖₊ g hg).2.2.1

end AlternatingAnalytic
