import AlternatingAnalytic.Analysis.LaurentField
import Mathlib.Algebra.Field.Subfield.Basic
import Mathlib.Algebra.Field.ZMod

/-!
# Lemma D.2 (Laurent subfield), p. 42

Paper statement: "Let K′ be a complete nontrivially normed field of characteristic p, and let
t ∈ K′ with 0 < |t| = r < 1.
(1) K′ is nonarchimedean, and |c| = 1 for every c ∈ 𝔽_p^×.
(2) For a_m, …, a_M ∈ 𝔽_p, not all zero, |∑_{i=m}^{M} a_i t^i| = r^{min{i : a_i ≠ 0}}.
(3) Give 𝔽_p((X)) the absolute value with |X| = r. There is a continuous isometric ring
homomorphism ev_t : 𝔽_p((X)) → K′ such that ev_t(∑_{i≥m} a_i X^i) = ∑_{i≥m} a_i t^i. Its
image K₁ is a closed subfield of K′; it is the closure of 𝔽_p(t), and it is isometrically
isomorphic to 𝔽_p((X)).
(4) K₁ is spherically complete."

Formalization notes:
* `p` is a prime with `[Fact p.Prime]` and `[CharP K′ p]`; `𝔽_p` is `ZMod p`, mapped into
  `K′` by the canonical ring hom `ZMod.castHom (dvd_refl p) K′`.
* (1): "nonarchimedean" is `IsUltrametricDist K′`; `c ∈ 𝔽_p^×` is `c ≠ 0`.
* (2): the coefficients are a function `a : ℤ → ZMod p` on the window `Finset.Icc m M`
  (negative indices allowed, as in the paper). Instead of `min{i : a_i ≠ 0}` the statement
  takes an index `i₀` in the window with `a i₀ ≠ 0` that is `≤` every index with nonzero
  coefficient; this is the minimum, and its existence is "not all zero". The right-hand side
  `r^{i₀}` is `‖t‖ ^ i₀` (integer power).
* (3), (4): `r` is a real number in `(0, 1)` given as `r : ℝ≥0` with `[Fact (0 < r)]`,
  `[Fact (r < 1)]` and `‖t‖ = r`. `𝔽_p((X))` with `|X| = r` is the library's type synonym
  `AlternatingAnalytic.LaurentField (ZMod p) r` of Mathlib's `LaurentSeries (ZMod p)`,
  normed by `‖x‖ = r ^ (order x)` (`AlternatingAnalytic/Analysis/LaurentField.lean`,
  imported for this definition only; it proves the normed-field structure, not this lemma).
  Its `i`-th coefficient is `LaurentField.coeff (ZMod p) r i`.
* (3): the evaluation formula is `HasSum (fun i : ℤ ↦ a_i t^i) (ev_t x)` with
  `a_i = coeff i x`, i.e. unconditional summation over `ℤ` (the terms vanish for `i` below the
  order, so this is the paper's series `∑_{i≥m}`). "Its image is a closed subfield" is
  `IsClosed` of `ev.fieldRange`; "the closure of 𝔽_p(t)" is the topological closure of
  `Subfield.closure {t}` (the subfield generated by `t`, which contains the prime field
  `𝔽_p`). "Isometrically isomorphic to 𝔽_p((X))" is not stated separately: it follows from
  `Isometry ev` (an isometry onto its range).
* (4) is stated intrinsically for `K₁ = closure (Subfield.closure {t})` (as a subtype of
  `K′` with the restricted metric), which by (3) is the image of `ev_t`.
* (4): `SphericallyCompleteSpace` is the library class from
  `AlternatingAnalytic/Analysis/SphericalCompleteness.lean`, imported transitively through
  `LaurentField.lean`. That module also holds the instance `SphericallyCompleteSpace
  (LaurentField κ r)`, which the statement does not use.
* No definitions are introduced.
-/

open scoped NNReal

namespace AlternatingAnalyticChallenge.LemD_2

universe u

open AlternatingAnalytic

/-- **Lemma D.2(1).** A complete nontrivially normed field of characteristic `p` is
ultrametric, and every nonzero element of `𝔽_p` has absolute value `1` in it. -/
theorem part1
    (K' : Type u) [NontriviallyNormedField K'] [CompleteSpace K']
    (p : ℕ) [Fact p.Prime] [CharP K' p] :
    IsUltrametricDist K' ∧
      ∀ c : ZMod p, c ≠ 0 → ‖ZMod.castHom (dvd_refl p) K' c‖ = 1 := by
  sorry

/-- **Lemma D.2(2).** A finite `𝔽_p`-combination `∑_{i=m}^{M} a_i t^i`, not all `a_i` zero,
has absolute value `‖t‖ ^ i₀`, where `i₀` is the least index with `a_{i₀} ≠ 0`. -/
theorem part2
    (K' : Type u) [NontriviallyNormedField K'] [CompleteSpace K']
    (p : ℕ) [Fact p.Prime] [CharP K' p]
    (t : K') (ht0 : 0 < ‖t‖) (ht1 : ‖t‖ < 1)
    (m M : ℤ) (a : ℤ → ZMod p) (i₀ : ℤ) (hi₀ : i₀ ∈ Finset.Icc m M) (ha : a i₀ ≠ 0)
    (hmin : ∀ i ∈ Finset.Icc m M, a i ≠ 0 → i₀ ≤ i) :
    ‖∑ i ∈ Finset.Icc m M, ZMod.castHom (dvd_refl p) K' (a i) * t ^ i‖ = ‖t‖ ^ i₀ := by
  sorry

/-- **Lemma D.2(3).** For `‖t‖ = r ∈ (0, 1)` there is a continuous isometric ring
homomorphism `ev_t : 𝔽_p((X)) → K′` (with `|X| = r`) sending `∑ a_i X^i` to `∑ a_i t^i`;
its image is a closed subfield of `K′` equal to the closure of `𝔽_p(t)`. -/
theorem part3
    (K' : Type u) [NontriviallyNormedField K'] [CompleteSpace K']
    (p : ℕ) [Fact p.Prime] [CharP K' p]
    (r : ℝ≥0) [Fact (0 < r)] [Fact (r < 1)] (t : K') (ht : ‖t‖ = r) :
    ∃ ev : LaurentField (ZMod p) r →+* K',
      Continuous ev ∧ Isometry ev ∧
      (∀ x : LaurentField (ZMod p) r,
        HasSum (fun i : ℤ => ZMod.castHom (dvd_refl p) K' (LaurentField.coeff (ZMod p) r i x) *
          t ^ i) (ev x)) ∧
      IsClosed (ev.fieldRange : Set K') ∧
      (ev.fieldRange : Set K') = closure (Subfield.closure {t} : Set K') := by
  sorry

/-- **Lemma D.2(4).** The closure `K₁` of `𝔽_p(t)` in `K′` is spherically complete. -/
theorem part4
    (K' : Type u) [NontriviallyNormedField K'] [CompleteSpace K']
    (p : ℕ) [Fact p.Prime] [CharP K' p]
    (t : K') (ht0 : 0 < ‖t‖) (ht1 : ‖t‖ < 1) :
    SphericallyCompleteSpace (closure (Subfield.closure {t} : Set K')) := by
  sorry

end AlternatingAnalyticChallenge.LemD_2
